network plot to map the color range to the range of correlations in data
tidymodels/corrr pull request #159
Opened 2022-05-11 13:05 UTC by thisisdaryn

This PR is in response to #158. 

`network_plot()` has been modified so that the `legend` argument now takes 3 possible values:

1. "full": the range of colors is mapped to -1 to 1 (this is 
2. "range": the range of colors is mapped to only the range of correlations found in the input `rdf`
3. "none" the range of colors is mapped to -1 to 1 without a legend being displayed.  This is equivalent to setting `legend` to `FALSE` in the previous implementation. 

Example of using `legend =  "full"`: 

`mtcars |>
  select(cyl, disp, hp, wt, carb) |> 
  correlate() |>
  network_plot(legend = "full")`

![option_full](https://user-images.githubusercontent.com/192906/167854401-c1941d36-97a6-4195-b52b-e9883267f72c.png)

Example of using `legend =  "range"`: 

`mtcars |>
  select(cyl, disp, hp, wt, carb) |> 
  correlate() |>
  network_plot(legend = "range")`
![option_range](https://user-images.githubusercontent.com/192906/167853844-3f8a807e-240e-4413-9ac1-c3a03fc741d8.png)

Example of using `legend =  "none"`: 

`mtcars |>
  select(cyl, disp, hp, wt, carb) |> 
  correlate() |>
  network_plot(legend = "none")`

![option_none](https://user-images.githubusercontent.com/192906/167854430-b8d60e2d-6f1d-451b-b496-221b59a728be.png)

Not specifying any of the options will default to using the full range with a displayed legend.
![default](https://user-images.githubusercontent.com/192906/167855668-856b4a70-ed0c-480f-adfc-fb73f9f54be8.png)

2022-05-13 03:42 UTC, juliasilge requested changes
Looks great! 🙌 

I made a minor change to the documentation for the new options. Want to take a look at `rlang::arg_match()`?

2022-05-13 03:42 UTC, juliasilge commented on R/cor_df.R
> +  legend <- match.arg(legend)
```suggestion
  legend <- rlang::arg_match(legend)
```

2022-05-15 18:49 UTC, merged

2022-05-15 18:55 UTC, juliasilge commented
Ooops @thisisdaryn it seems like something went a little wonky with git here. It looks like the PR was to the `add_range_option` branch instead of to `main`. I didn't notice this until after I merged the PR, so I did another PR #160 to merge into main. No big deal but in the future, you might want to make sure you are setting up a PR to the main branch.

2022-05-15 21:49 UTC, thisisdaryn commented
> Ooops @thisisdaryn it seems like something went a little wonky with git here. It looks like the PR was to the `add_range_option` branch instead of to `main`. I didn't notice this until after I merged the PR, so I did another PR #160 to merge into main. No big deal but in the future, you might want to make sure you are setting up a PR to the main branch.

Noted. My bad. Will look out for that in the future. Thanks.